### ISSUE TITLE
index no longer updates

### ISSUE THREAD

**Issue by lastmoexit** [skrul/greasefire#65]
using Firefox 3.6.25 (Greasefire v1.04; Greasemonkey v0.8.20100408.6), Greasefire index will no longer update past 2012-01-20  ...when update button is clicked, immediately says "Error updating: status = 0x0 http = 404" ...able to manually update from http://skrul.com/projects/greasefire/indexes/

**Comment by frog23** [comment]
I can confirm this. This bug is independent of Firefox, Greasefire or Greasemonkey, but an error in the server providing the indexes. Greasefire calls http://skrul.com/projects/greasefire/update.php which forwards to (today) http://skrul.com/projects/greasefire/indexes/index_2012-01-24T10:00:00Z.jar which does not exist, as does the file for 2012-01-23. The corresponding folders (like 2012-01-23T10:00:00Z/) are created, but are empty.

**Comment by tykiwabydaloc** [comment]
I have the same problem "Error updating: status = 0x0 http = 404"
MFF 9.0 with Scriptish + all newest MFF plugins and addons + all newest W XP patches + all newest Comodo ISP patches

**Comment by lastmoexit** [comment]
everything is working fine now ...thank you ...peace
