### ISSUE TITLE
Remove use of <em:unpack>true</em:unpack>

### ISSUE THREAD

**Issue by erikvold** [skrul/greasefire#7]
`<em:unpack>true</em:unpack>` slows the start-up time, so we should alter `makexpi.sh` so that we can remove `<em:unpack>true</em:unpack>`

**Comment by tony1223** [comment]
The problem is how we could get the included database which location in firefox\indexes folder ,

As what I know , we have following thing to do ,
need to change GF_GetIndexesDir in gfGreasefireService.js to find a better way instead of directoryService.

It might not be a easy job since it require sync process ,
and the add-on process was changed to async in FF4,any ideas to this?

That's the only issue I think.

**Comment by erikvold** [comment]
> As what I know , we have following thing to do , need to change GF_GetIndexesDir in gfGreasefireService.js to find a better way instead of directoryService.

Hmm, well the easy (and perhaps not the best) solution that I see here is to store these `indexes` folder outside of the extension. We may be able to compress the `indexes` folder and drop that in the user's profile dir with a name like `greasefire_indexes_20110509.jar`, I've not tried that with a DB b4 tho.

If we must store the indexes with the extension, then we could store updated indexes in another directory, the downside here would be that we use more HD space.

Otherwise I guess we will have to live with unpack.

**Comment by erikvold** [comment]
It might be possible to simply add and remove files from the xpi as well.

**Comment by erikvold** [comment]
I kind of prefer the jar idea I mentioned first tho, if it works..

**Comment by tony1223** [comment]
That sounds not bad , could try to implement it.

**Comment by skrul** [comment]
It makes total sense to store the indexes in the user's profile rather than inside the extension dir.  I don't remember why I did it that way exactly -- it may be because I wanted to ship a copy of the indexes with the extension itself so the extension will work immediately after installing... and I was too lazy to move it :)

Ideally we could add a "greasefire@skrul.com" directory in the user's profile directory and store the indexes in there.  Upon startup, the extension would check the info.ini file in that directory and compare it to the info.ini that ships along with the indexes in the xpi.  If the indexes in the xpi are newer or the directory does not yet exist in the user's profile, copy them over.  Then we just need to change the directory that the updater writes the newly downloaded indexes to.

Thoughts?

**Comment by erikvold** [comment]
> Upon startup, the extension would check the info.ini file in that directory and compare it to the info.ini that ships along with the indexes in the xpi. If the indexes in the xpi are newer or the directory does not yet exist in the user's profile, copy them over. Then we just need to change the directory that the updater writes the newly downloaded indexes to.

This sounds good to me.

**Comment by erikvold** [comment]
#41 is a follow-up
